target_dict_mapping = {
    'target-hemoglobin-grade2plus': 'Hb',
    'target-neutrophil-grade2plus': 'ANC',
    'target-bilirubin-grade2plus': 'Bili',
    'target-platelet-grade2plus': 'PLT',
    'target-ALT-grade2plus': 'ALT',
    'target-AST-grade2plus': 'AST',
    'target-AKI-grade2plus': 'AKI',
    'target-death-in-30d': '30d death',
    'target-death-in-365d': '1y death',
    'target-ED-visit': 'ED visits',
    'target-esas-depression-3pt-change': 'Depression',
    'target-esas-pain-3pt-change': 'Pain',
    'target-esas-anxiety-3pt-change': 'Anxiety',
    'target-esas-tiredness-3pt-change': 'Tired',
    'target-esas-nausea-3pt-change': 'Nausea',
    'target-esas-drowsiness-3pt-change': 'Drowsy',
    'target-esas-appetite-3pt-change': 'Appetite',
    'target-esas-well-being-3pt-change': 'Well-being',
    'target-esas-shortness-of-breath-3pt-change': 'Dsypnea',
}
